version: "3.4"
services:
  spring-boot-kafka-multiple-brokers:
    build: spring-boot-kafka-multiple-brokers
    container_name: 'spring-boot-kafka-multiple-brokers'
    environment:
      - spring_profiles_active=docker
    ports:
      - 8081:8081
    networks:
      - kafka-network

networks:
  kafka-network:
    external: true
    name: kafka-network