version: "3.4"
services:
#  spring-boot-kafka-multiple-brokers:
#    build: ./spring-boot-kafka-multiple-brokers
#    container_name: 'spring-boot-kafka-multiple-brokers'
#    environment:
#      - spring_profiles_active=docker
#      - KAFKA_1_HOST=kafka-1
#      - KAFKA_2_HOST=kafka-2
#    ports:
#      - 8081:8081
#    networks:
#      - kafka-network
  zookeeper-1:
    image: 'bitnami/zookeeper:latest'
    container_name: 'zookeeper-1'
    ports:
      - '12181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - kafka-network
  kafka-1:
    image: 'bitnami/kafka:latest'
    container_name: 'kafka-1'
    ports:
      - '19092:19092'
      - '19093:19093'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:19092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:19092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-1:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:19092,EXTERNAL://:19093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka-1:19092,EXTERNAL://localhost:19093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper-1
    networks:
      - kafka-network
  zookeeper-2:
    image: 'bitnami/zookeeper:latest'
    container_name: 'zookeeper-2'
    ports:
      - '22181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - kafka-network
  kafka-2:
    image: 'bitnami/kafka:latest'
    container_name: 'kafka-2'
    ports:
      - '29092:29092'
      - '29093:29093'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:29092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-2:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:29092,EXTERNAL://:29093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka-2:29092,EXTERNAL://localhost:29093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper-2
    networks:
      - kafka-network
#  zookeeper-1:
#    image: confluentinc/cp-zookeeper:latest
#    container_name: zookeeper-1
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#      ZOOKEEPER_TICK_TIME: 2000
#    ports:
#      - 22181:2181
#    networks:
#      - kafka-network
#
#  zookeeper-2:
#    image: confluentinc/cp-zookeeper:latest
#    container_name: zookeeper-2
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#      ZOOKEEPER_TICK_TIME: 2000
#    ports:
#      - 32181:2181
#    networks:
#      - kafka-network
#
#  kafka-1:
#    image: confluentinc/cp-kafka:latest
#    container_name: kafka-1
#    depends_on:
#      - zookeeper-1
#      - zookeeper-2
#    ports:
#      - 29092:29092
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092,PLAINTEXT_HOST://localhost:29092
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#    networks:
#      - kafka-network
#
#  kafka-2:
#    image: confluentinc/cp-kafka:latest
#    container_name: kafka-2
#    depends_on:
#      - zookeeper-1
#      - zookeeper-2
#    ports:
#      - 39092:39092
#    environment:
#      KAFKA_BROKER_ID: 2
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092,PLAINTEXT_HOST://localhost:39092
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#    networks:
#      - kafka-network

networks:
  kafka-network:
    name: kafka-network
    driver: bridge