version: "3.4"
services:
  zookeeper-1:
    image: 'bitnami/zookeeper:latest'
    container_name: 'zookeeper-1'
    ports:
      - '12181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - kafka-network

  kafka-1:
    image: 'bitnami/kafka:latest'
    container_name: 'kafka-1'
    ports:
      - '19092:19092'
      - '19093:19093'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:19092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:19092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-1:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:19092,EXTERNAL://:19093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka-1:19092,EXTERNAL://localhost:19093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper-1
    networks:
      - kafka-network

  zookeeper-2:
    image: 'bitnami/zookeeper:latest'
    container_name: 'zookeeper-2'
    ports:
      - '22181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - kafka-network

  kafka-2:
    image: 'bitnami/kafka:latest'
    container_name: 'kafka-2'
    ports:
      - '29092:29092'
      - '29093:29093'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:29092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-2:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:29092,EXTERNAL://:29093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka-2:29092,EXTERNAL://localhost:29093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper-2
    networks:
      - kafka-network

networks:
  kafka-network:
    name: kafka-network
    driver: bridge