user-kafka:
  bootstrap-servers: "${KAFKA_1_HOST}:19092"
  listener:
    missing-topics-fatal: false
bank-kafka:
  bootstrap-servers: "${KAFKA_2_HOST}:29092"
  listener:
    missing-topics-fatal: false