server:
  port : 8081
spring:
  profiles:
    active: local
  application:
    name: "spring-boot-kafka-multiple-brokers"
user-kafka:
  bootstrap-servers: "localhost:19093"
  listener:
    missing-topics-fatal: false
bank-kafka:
  bootstrap-servers: "localhost:29093"
  listener:
    missing-topics-fatal: false